export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as News } from "./News";
export { default as Corevalues } from "./corevalues";
export { default as Tatca } from "./Tatca";
export { default as History } from "./history";
export { default as Partn } from "./PartnerHome";
export { default as K_SOLUTION } from "./sanpham/K_SOLUTION";
export { default as K_HEALTHTECH } from "./sanpham/K_HEALTHTECH";
export { default as  K_TECHNICAL } from "./sanpham/K_TECHNICAL";
export { default as Slide } from "./slidebar";
export { default as MutiProduct } from "./item/MutiProduct";
export { default as AboutItem } from "./item/AboutItem";
export { default as MutiSanPham } from "./item/MutiProduct";
export { default as MutiTeam } from "./item/MutiTeam";
export { default as TopNews } from "./item/TopNews";
export {default as TamNhin} from "./item/TamNhin";
export {default as  IntroAbout} from "./item/IntroAbout";
export {default as  Banner} from "./child/banner";